name: Generate API

on: push

jobs:

    generate_api:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Prompt to Generate API
          run: |
            read -p "Do you want to generate the API? (y/n): " answer
            if [[ $answer =~ ^[Yy]$ ]]; then
                # Run your script to generate the API
                python docs/user/generate_api.py
            fi 